### PR TITLE
winevulkan: fshack cleanup + unwrap swapchain.

### PR DESCRIPTION
**Pull request by DadSchoorse**
Additionally to the other wrapped handles proton's winevulkan also wraps VkSwapchainKHR for fshack. Also includes some cleanup that was missed in past fshack changes.

The second commit needs regenerating with `./make_vulkan`. I wasn't about the preferred way for this repo, patches on wine-devel don't regenerate anything.

### CODE REVIEW

**Comment by aeikum** [comment]
Thanks, I'll take a look. Does this fix any problems, or just some general cleanup?

**Comment by DadSchoorse** [comment]
The second commit (everything I originally wanted to do) fixes crashes when swapchains are passed as `uint64_t`, e.g. in `vk{Get,Set}PrivateDataExt` and `vkSetDebugUtilsObjectNameEXT`. There are no actual games which are effected by this yet afaik.
The other two are just cleanup.

**Comment by aeikum** [comment]
@DadSchoorse The 2nd commit in this series has a build failure. Looks like it needs make_vulkan re-run. That fixes the build error for me, but can you check that's what you intended to do?

**Comment by DadSchoorse** [comment]
> @DadSchoorse The 2nd commit in this series has a build failure. Looks like it needs make_vulkan re-run. That fixes the build error for me, but can you check that's what you intended to do?

Yes, I mentioned that in the top comment. :slightly_smiling_face: 

 If you want I can regenerate in future, as I said I did what I would do on wine-devel.

**Comment by aeikum** [comment]
D'oh, sorry.  Either way's fine, though if you do the regeneration, it's one less thing for me to screw up.

**Comment by aeikum** [comment]
I've included these in the Experimental branch. I plan to pull them into the main branch whenever we do another release there.

**Comment by DadSchoorse** [comment]
@aeikum This seems to be included in 3b4caa1dbdfe3dbe0d41ccca54f091313403f8d5, so I can probably close this PR?

**Comment by aeikum** [comment]
Yep, thanks!

**Pull request closed without merging**
