### PR TITLE
user32: Check invalid handle in GetRawInputData.

### PR DESCRIPTION
**Pull request by zzhiyi**
Fix https://github.com/ValveSoftware/Proton/issues/2040.

Signed-off-by: Zhiyi Zhang <zzhang@codeweavers.com>

### CODE REVIEW

**Comment by zzhiyi** [comment]
Also https://github.com/ValveSoftware/Proton/issues/1819

**Comment by aeikum** [comment]
Thanks. Can this go upstream after code freeze?

**Comment by zzhiyi** [comment]
> Thanks. Can this go upstream after code freeze?

It's already on wine-devel :)

**Comment by aeikum** [comment]
This was included in the 3.16-7 release. e8b658c6f8c

**Pull request closed without merging**
