### PR TITLE
Implement integer scaling in fshack

### PR DESCRIPTION
**Pull request by misyltoad**
This adds the env var PROTON_FSHACK_INTEGER_SCALING to do nearest neighbour upscaling for fshack.

May help out some users playing pixel art titles at lower resolutions for UI scale or other reasons.

### CODE REVIEW

**Comment by misyltoad** [comment]
Maybe I should rename this as it's not *true* integer scaling.

Could do some more work to ensure we upscale to the biggest multiple we can fit and black border around the rest of it though -- which would make it accurate.

**Comment by aeikum** [comment]
This is a great idea. I probably won't have time to look at it for a few days or a week or two (sorting through DXGI-related regressions at the moment...). We are also making some fshack-related changes due to Zhiyi's work on multiple monitor support, so there may be some conflicts there. Anyway, cool stuff, will take a look as soon as I can.

**Comment by aeikum** [comment]
> Maybe I should rename this as it's not _true_ integer scaling.
> 
> Could do some more work to ensure we upscale to the biggest multiple we can fit and black border around the rest of it though -- which would make it accurate.

I think that'd be a neat improvement, yeah.

**Comment by misyltoad** [comment]
Is it worth me waiting for that other work to land first before I do that?

These changes were very basic and I don't mind re-making them.

**Comment by aeikum** [comment]
That stuff won't land until the next rebase. If you want to do it now that should be fine, we'll port it over during the rebase.

**Comment by misyltoad** [comment]
I have force pushed my implementation of true integer scaling.

**Comment by aeikum** [comment]
Cool! Do you have a couple suggested games to try it out with?

**Comment by misyltoad** [comment]
Force pushed some OpenGL optimizations for it

**Comment by misyltoad** [comment]
Currently I have been testing with Half-Life 2

``PROTON_FSHACK_INTEGER_SCALING=1 PROTON_USE_D9VK=1 %command% -w 1024 -h 768 -fullscreen``

(1024x768 does not divide nicely into 1920x1080 or 3840x2160)

**Comment by misyltoad** [comment]
What should happen:

IMG_20191120_190100

:tada:

**Comment by zzhiyi** [comment]
This change doesn't seem too big. Let's pull it in before my multiple monitor support lands. I will do a rebase for it.

**Comment by aeikum** [comment]
Filtered:

dx_fs

Integer scaling:

dx_integer

I like it!

One outstanding problem is how/when to turn this on. Obviously we can have user overrides for it, but does it make sense to have some attempt at auto-enabling it? Maybe something like if either dimension is less than half of the real dimension; or if `(desired X * desired Y) < (real X * real Y) / 4` or something. Have other projects encountered this? Do any classic console emulators have "smart" selection between filtering and pixel doubling?

**Comment by misyltoad** [comment]
We wouldn't want to do this automatically... I think an option in Steam would be nice per-gane, with maybe a default in the appinfo.

**Comment by aeikum** [comment]
You might be right, but I think it's at least worth thinking about. In what situations would a user want this enabled? One obvious application is older pixel games (although it seems most such releases on Steam already do their own scaling rather than mode switching), but we can't filter by that programmatically. I'd argue the unfiltered Deus Ex screenshot above looks better than the linear filtering, although it does have the downside of being both letter- and pillar-boxed.

I played around with the options a bit and less than half in *both* dimensions seems like a reasonable heuristic to me. I think it's also going to be a fairly rare case (even 800x600 is greater than half of my monitor's height), although high DPI monitors may be changing that.

    BOOL fs_hack_is_integer(void)
    {
        static int is_int = -1;
        if(is_int < 0)
        {
            const char *e = getenv("WINE_FULLSCREEN_SCALING");
            if(e && !strcmp(e, "pixel"))
                is_int = 1;
            else if(e && !strcmp(e, "smooth"))
                is_int = 0;
            else
                return (dd_modes[currentMode].width <= dd_modes[realMode].width / 2) &&
                    (dd_modes[currentMode].height <= dd_modes[realMode].height / 2);
        }
        return is_int;
    }

I dunno. Any thoughts?

**Comment by pchome** [comment]
@aeikum 
> I'd argue the unfiltered Deus Ex screenshot above looks better than the linear filtering, although it does have the downside of being both letter- and pillar-boxed.

An option to force borderless-window mode would be great. Like `-popupwindow` command line argument in some Unity engine games ("-popupwindow (Windows only) | The window will be created as a a pop-up window (without a frame)").

Look and feel will depend on game itself and on user's preference. Pixel-art should look great, but user may also want to use scaling when e.g. on the couch, with big screen in other side of the room. So my vote for an option.

Also, I'm not sure about this patch, but I tested so-called "RETRO" mode from [libstrangle](https://gitlab.com/torkel104/libstrangle/blob/master/src/vulkan.c#L127) with Wasteland 2: DC, and it looked good in both scaling modes for me.

**Comment by misyltoad** [comment]
@aeikum The problem with that is you get games that wanna use a mode very close to your display res that are pixel art. I dont think this is a good enough heuristic... Some people may dislike that we're upscaling this way by default in some titles where it doesn't really fit.

**Comment by aeikum** [comment]
Yeah, that's a good point. I guess setting it manually (either the user, or us via app defaults) is the way to go.

**Comment by aeikum** [comment]
I merged this with a couple trivial changes. The most significant is this change to your environment variable name:

    BOOL fs_hack_is_integer(void)
    {
        static int is_int = -1;
        if(is_int < 0)
        {
            const char *e = getenv("WINE_FULLSCREEN_INTEGER_SCALING");
            is_int = e && strcmp(e, "0");
        }
        return is_int;
    }

In general, I like to avoid using "Proton" from within Wine, as these commits may get applied to other projects (wine-staging, etc).

**Comment by misyltoad** [comment]
You could make another function to get the value and do `static int is_int = fs_hack_is_integer_value();` and then return that to avoid the if statement.

(Assuming I haven't used a C++-ism there)

**Comment by aeikum** [comment]
Good idea, I think that should work fine.

**Comment by aeikum** [comment]
Or not. Was worth a shot.

    ../../../../proton/wine/dlls/winex11.drv/settings.c: In function 'fs_hack_is_integer':
    ../../../../proton/wine/dlls/winex11.drv/settings.c:285:25: error: initializer element is not constant
         static int is_int = check_integer_scaling_env();
                             ^
    make: *** [Makefile:575: settings.o] Error 1

**Comment by misyltoad** [comment]
Yeah I thought it might be a C++ism...

Wine moving to C++ it is then :)))) 🐸🐸🐸🐸🐸

**Comment by aeikum** [comment]
Heh. [Did you know `g++` intentionally breaks `dlclose`?](https://github.com/ValveSoftware/Proton/commit/bd8efaa9a63310382a92763fd44c9f8cfbabada7) That one was fun to debug. I wonder what other headaches that way lie ;)

**Comment by pchome** [comment]
BTW, isn't env vars have "three states"?
* not set
* empty (`VAR=`)
* value (`VAR=0`)

defined / initialized ...

Sorry for the noise if I'm wrong.

**Comment by kakra** [comment]
> I dunno. Any thoughts?

Yes, I have some: I'm using a UHD screen but need to scale a lot of games to QHD, and a few to FHD. FHD would be half resolution of UHD, so your heuristic may already kick in.

Let's assume something different: Either, modern pixel art games do their own scaling (or you could just run them at native or near-native resolution without performance problems), or they are very old and max out at some legacy resolutions. So the heuristic should look for resolutions below or equal to 1024x768, or for 4:3 resolution below 1/4th of the native pixel density. In pseudo-code:

```
if (res <= '1024x768' || (aspect <= 4/3 && running_megapixels <= native_megapixels/4)) { ... }
```

What do you think? Looking at the pixel count, a factor of 4 counts for half resolution as you already suggested, only that we also expect the aspect to be 4:3 (or less, so more quadratic than wide). Maybe we can tune the aspect ratio parameter a bit more. But I think legacy pixel-art games are either very low resolution or use 4:3 aspect ratio and somewhat low resolutions.

Still, I'm having some bad taste about this heuristic: It incorporates a value that is potentially only growing over time... The native screen resolution... We should strictly avoid such variables. Maybe better compare against static FHD pixel count, no matter what the future brings, e.g. `... running_megapixels <= FHD_megapixels`?

**UPDATE:** Let's compare to 8/5 instead of 4/3 so we would catch legacy resolutions of 320x200, too.

**Comment by Marat-Tanalin** [comment]
## Heuristics idea: enable IS based on pixel density

One of reliable-enough heuristic approaches would probably be to enable integer scaling automatically if the native/logical ratio is lower than or equal to OS-level _pixel density_ (DPI, PPI).

For example, if the user has OS-level zoom set to 200% (2.0), it’s probably safe to assume that logical pixels are small enough to be almost indistinguishable at that ratio. This is the case e.g. when playing antialiased 3D games at FHD on a 24-27″ 4K monitor with 200% OS-level zoom.

In future, with a 8K monitor of the same size and OS-level zoom of 400% (4.0), integer scaling could be automatically enabled at any logical resolution resulting in a lower ratio such as 300% or 200%. So at OS-level zoom of 400%, we would get integer scaling in Proton automatically enabled for FHD (400%, logical pixels are small enough), QHD (300%, even smaller pixels), and 4K (200%, even more smaller pixels).

The behavior could be controlled via an option with the following list of possible values:

* Auto _[integer scaling is enabled heuristically according to pixel density and maybe something else]_
* Enabled _[integer scaling is enabled always, no heuristics magic]_
* Disabled _[regular blurry interpolation is used]_

The “Auto” value could probably be used by default.

**Comment by aeikum** [comment]
This was merged as 157a4b8c0dada5020b73549f2eea4aea6838b1cc and is available in 4.11-10 with `WINE_FULLSCREEN_INTEGER_SCALING=1`. We can move the heuristic discussion to a new Issue or something, although I haven't yet seen a clear case where every user would prefer to use this mode. Maybe we should find one and base our discussion on that.

**Comment by soredake** [comment]
@Joshua-Ashton is this working correctly?
with integer:
integer
without integer:
non_integer

**Comment by misyltoad** [comment]
Yes.

**Comment by misyltoad** [comment]
If you can't fit it in an integer scale factor, you get black borders around it.

**Comment by Marat-Tanalin** [comment]
@soredake

`1080 / 600 = 1.8`, so the largest integer is `1`, and the rest `0.8` is filled with black, which is equivalent to regular centered mode.

For 800×600, the best-fit native heights are 1200 (2x, perfect fit) and 4320 (8K, 7x, just 3% of height lost).

Less optimal are 1440 (2x) and 4K (3x) with 17% of height lost in both cases.

1080 is only enough for 640×480 (2x, 11% of height lost) and lower resolutions.

**Comment by Marat-Tanalin** [comment]
@Joshua-Ashton
Is the feature already available in the Proton version built into stable Steam?

**Comment by kisak-valve** [comment]
Hello @Marat-Tanalin, yes, see https://github.com/ValveSoftware/wine/pull/69#issuecomment-565526767.

**Comment by soredake** [comment]
@Joshua-Ashton @Marat-Tanalin thanks

switched to 640x480:
Screenshot_20200228_194049

**Comment by soredake** [comment]
Same happens in dead space, but only after alt-tab, and cursor is doubled:
Screenshot_20200228_201307

**Comment by pchome** [comment]
@Joshua-Ashton 
I guess you could try to emulate 21:9 with Wine virtual desktop [1720x720](https://en.wikipedia.org/wiki/Ultrawide_formats#Ultrawide_Cinema) resolution on regular monitor. Then test both integer and regular scaling mode with 720 and 360.

I can confirm, this is how (see above comment) integer scaling work on 21:9 monitor. Also, sometimes scaling is wrong in FS-hack mode, but I can't remember where and how.

**Pull request closed without merging**
