### PR TITLE
dxdiagn improvements for Rainbow Six: Lockdown

### PR DESCRIPTION
**Pull request by gverm**
These commits fix a crash on startup in the game Tom Clancy's Rainbow Six: Lockdown. The relevant wine bugs are in the commit messages and the crash was also mentioned in https://github.com/ValveSoftware/Proton/issues/2862.

### CODE REVIEW

**Comment by aeikum** [comment]
Thanks, we'll take a look.

**Comment by gverm** [comment]
@aeikum Any word on this?

**Comment by aeikum** [comment]
Looks like it slipped through the cracks, sorry. I've filed a bug in our internal tracker for it so it shouldn't get lost again.

**Comment by gverm** [comment]
I'll close this since it is automatically included in proton-6.3 and the game was mentioned in the Changelog as well.

**Pull request closed without merging**
