### PR TITLE
winex11.drv: Add 1620p and 1800p 16:9 resolutions to the FS hack.

### LINKED ISSUE #1955: Steam Play miss 1800p resolution
Add the option for 3200x1800 resolution, it´s a very common resolution on Game consoles and gives a 4K image quality with lower system resource usage. It shoud be integrated into proton instead wine as it is a game driven application.

### PR DESCRIPTION
**Pull request by Tk-Glitch**
These are commonly used on QHD+ and 4k displays for performance.

Fixes https://github.com/ValveSoftware/Proton/issues/1955

### CODE REVIEW

**Comment by aeikum** [comment]
Can you post the output of `xrandr` on a machine with this display?

**Comment by Tk-Glitch** [comment]
I sadly do not have such a display myself. This was initially a feature request for my alternative wine/proton build system, made by a 4k display user. From the reports in #1955 and other users feedback, it seems these resolutions are - at least on some displays - not exposed.

Thanks to @lordkitsuna who has graciously provided `xrandr` output of his dual 4k displays setup:
```
Screen 0: minimum 320 x 200, current 6000 x 3840, maximum 16384 x 16384
DisplayPort-0 connected primary 3840x2160+2160+1680 (normal left inverted right x axis y axis) 620mm x 350mm
   3840x2160     60.00*+
   2560x1440     59.95  
   2048x1536     60.02  
   1920x1200     60.00  
   1920x1080     60.00    50.00    59.94  
   1600x1200     60.00  
   1680x1050     59.95  
   1600x900      60.00  
   1280x1024     75.02  
   1440x900      59.89  
   1280x800      59.81  
   1280x720      60.00    50.00    59.94  
   1024x768      75.03    70.07    60.00  
   800x600       72.19    75.00    60.32    56.25  
   720x576       50.00  
   720x480       60.00    59.94  
   640x480       75.00    72.81    60.00    59.94  
   720x400       70.08  
DisplayPort-1 connected 2160x3840+0+0 right (normal left inverted right x axis y axis) 600mm x 340mm
   3840x2160     60.00*+  30.00  
   2560x1440     59.95  
   1920x1200     60.00  
   1920x1080     60.00    59.94  
   1600x1200     60.00  
   1680x1050     60.00  
   1600x900      60.00  
   1280x1024     60.02  
   1440x900      60.00  
   1280x800      59.81  
   1152x864      59.97  
   1280x720      60.00    59.94  
   1024x768      60.00  
   800x600       60.32  
   720x480       60.00    59.94  
   640x480       60.00    59.94  
```

Edit: Thanks to Jonty and Serebit over discord for providing more:
```
Screen 0: minimum 320 x 200, current 5377 x 2160, maximum 16384 x 16384
DisplayPort-0 connected primary 3840x2160+1537+0 (normal left inverted right x axis y axis) 607mm x 345mm
   3840x2160     60.00*+  30.00    29.97  
   2560x1440     59.95  
   1920x1200     60.00  
   1920x1080     60.00    59.94  
   1600x1200     60.00  
   1680x1050     59.95  
   1600x900      60.00  
   1280x1024     75.02    60.02  
   1440x900      59.89  
   1280x800      59.81  
   1152x864      75.00  
   1280x720      60.00    59.94  
   1024x768      75.03    70.07    60.00  
   832x624       74.55  
   800x600       72.19    75.00    60.32    56.25  
   640x480       75.00    72.81    66.67    60.00    59.94  
   720x400       70.08  
```

https://hastebin.com/aruvogadej (verbose)

**Comment by aeikum** [comment]
Great, thanks. 700 rows is indeed quite a big jump. Will merge.

**Comment by Tk-Glitch** [comment]
Thanks!

**Comment by aeikum** [comment]
This was merged as 9ad09babd5c9758ce6a5433f490e5590ce3956df. Thanks!

**Pull request closed without merging**
