### PR TITLE
changes for working resident evil 4

### PR DESCRIPTION
**Pull request by jomarocas**
this patch have taken from winehq https://bugs.winehq.org/attachment.cgi?id=63649

### CODE REVIEW

**Comment by kisak-valve** [comment]
Upstream bug report: https://bugs.winehq.org/show_bug.cgi?id=46336#c8

**Comment by jomarocas** [comment]
Black flag Upstream bug report: 
https://bugs.winehq.org/show_bug.cgi?id=39731#c8
Residen evil 4 Upstream bug report: 
https://bugs.winehq.org/show_bug.cgi?id=46336#c8

**Comment by aeikum** [comment]
Superseded by #55.

**Comment by jomarocas** [comment]
hi @aeikum this merge also in proton 4.2? because i create two merge request for different version, thanks

**Comment by aeikum** [comment]
Proton 3.16 won't be getting any more updates.

**Pull request closed without merging**
