### PR TITLE
Add Support For Native Raw-Input using XInput2

### PR DESCRIPTION
**Pull request by Guy1524**
This patchset uses XInput2's RawMotion feature to send mouse movement values that are not affected by the DE's settings for sensitivity or mouse acceleration.  It also implements RIDEV_NOLEGACY, which fixes multiple bugs.

This patchset also fixes the clipping issue w/ GTAV's RawInput setting.

### CODE REVIEW

**Comment by aeikum** [comment]
This is still working its way upstream. I'd like to see the kinks worked out first before we merge it.

**Comment by Guy1524** [comment]
@aeikum What kinks?  Remi has sent me a signed off variant of this patchset which I have slightly modified for proton in this PR.  The complaints Zebediah have are entirely stylistic.

**Comment by misyltoad** [comment]
Yeah I'm not aware of any issues with this patchset, have been using it for a while and it greatly improves the experience in Source games with m_rawinput.

**Comment by aeikum** [comment]
> @aeikum What kinks? Remi has sent me a signed off variant of this patchset which I have slightly modified for proton in this PR. The complaints Zebediah have are entirely stylistic.

winex11 in proton is already kind of a mess. If you can get them upstreamed, then we can lose that commit you reverted and replace it with upstream cherry-picks. That means reducing our diff instead of growing it. It sounds like it's already almost all the way upstreamed, so I'd like to wait for that before applying to Proton.

**Comment by Mel34** [comment]
There are kinks and Guy 1524 is aware of them, I've personality let him know about it on lutris discord. His patches breaks mouse camera control in Guild wars 2. I know it's not a steam game, but it's a proof it's not perfected yet. Thank you.

**Pull request closed without merging**
