### PR TITLE
.update added get_FMA3_enable function

### PR DESCRIPTION
**Pull request by daxcore**
necessary for eFootball PES 2020 (appId=996470).
fixes the startup crash described here: https://github.com/ValveSoftware/Proton/issues/3227

### CODE REVIEW

**Comment by kisak-valve** [comment]
Hello @daxcore, can you also send this to wine's mailing list so that it can get merged upstream?

**Comment by daxcore** [comment]
> Hello @daxcore, can you also send this to wine's mailing list so that it can get merged upstream?

Hey @kisak-valve,

I did this already here: https://github.com/wine-mirror/wine/pull/17
I hope the wine-mirror will synced somehow with original.

**Comment by nsivov** [comment]
This wine-mirror repo has no affiliation with Wine project, and isn't used for development. Please take a look at patch submitting guide here https://wiki.winehq.org/Submitting_Patches

**Comment by jqadev** [comment]
@aeikum please merge it with the upcoming Proton release :)

**Comment by aeikum** [comment]
Thanks for working to upstream this. I'll keep an eye on their progress over there.

**Comment by daxcore** [comment]
https://www.winehq.org/pipermail/wine-devel/2020-February/158862.html
I hope this one will be okay for the official wine project.

**Comment by jqadev** [comment]
@aeikum there are no messages in the mailing list since Tuesday related to `get_FMA3_enable` after discussions and improvements of the patch.
Do you think the final form of the function from the mailing list is already in good shape and will be merged here and will be available in the upcoming Proton release?

**Comment by aeikum** [comment]
We're late in the next release cycle, so it won't make it into the next build. I'm hoping the authorship thing will get resolved in the meantime. Upstreamed patches are _much_ less work for me to manage.

**Comment by jqadev** [comment]
@daxcore WINE developer asked you here https://www.winehq.org/pipermail/wine-devel/2020-February/159011.html to use your real name in the submitted patch.
Maybe it is a blocker of merging your patch.

**Comment by jqadev** [comment]
@kisak-valve, it's been solved in https://github.com/ValveSoftware/wine/commit/1fc1f153b17b47929dd6a164dcb8eb133bf0d946
Can be closed.

**Pull request closed without merging**
