### PR TITLE
advapi32: Add EventWriteString stub.

### LINKED ISSUE #2616: Are you ready for Valve Index? (1070910)
# Compatibility Report
- Name of the tool with compatibility issues: Are you ready for Valve Index?
- Steam AppID of the tool: 1070910

## System Information
- GPU: GeForce GTX 1060 6GB
- Driver/LLVM version: nvidia 418.56
- Kernel version: 5.0.10
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/Scrumplex/0ff9dbca5e62327824263ecdde4ef55d
- Proton version: 4.2-3

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-1070910.log](https://github.com/ValveSoftware/Proton/files/3132722/steam-1070910.log)

## Symptoms
Crashes while checking

## Reproduction
Click on the check system button.

### PR DESCRIPTION
**Pull request by ryao**
This fixes ValveSoftware/Proton#2616.

### CODE REVIEW

**Comment by ryao** [comment]
This makes "Are you ready for Valve Index?" go from crashing during its test to reporting the following:

image

I find this preferable to the current behavior.

**Comment by ryao** [comment]
Also, this patch doesn't apply against wine 4.14 because wine-mirror/wine@f535bcb2e66153301f1927a9a323c1e989c49cd5 moved the stubs. I rebased it and sent the rebased version to wine-devel@.

**Comment by ryao** [comment]
The wine 4.14 version of this patch is now visible in the wine-devel archive:

https://www.winehq.org/pipermail/wine-devel/2019-August/149748.html

**Comment by ryao** [comment]
The version submitted to wine-devel has passed the test bot:

https://testbot.winehq.org/JobDetails.pl?Key=55596

**Comment by ryao** [comment]
This patch has been accepted into wine:

https://source.winehq.org/git/wine.git/commit/f535bcb2e66153301f1927a9a323c1e989c49cd5

**Comment by ryao** [comment]
The patch is now in Wine:

https://github.com/wine-mirror/wine/commit/8d5554247338acdb3ed94668115f73be667378fd

**Comment by aeikum** [comment]
Nice work! Will merge.

**Comment by aeikum** [comment]
This was merged as 6a53a746b78e8197506ea2d43ec1f5273f02f6a5. Thanks!

**Pull request closed without merging**
