### PR TITLE
HACK: ntdll: Return a handle to kernel32 when being asked for mfc42.

### LINKED ISSUE #2624: Add MFC42.dll "loader hack", which helps multiple games.
# Feature Request

## I confirm:
- [x] that I haven't found another request for this feature.
- [x] that I have checked whether there are updates for my system available that
      contain this feature already.

## Description 

Add "loader hack" to pretend to load ```mfc42```:
1. During ```LoadLibrary```detect if app uses ```mfc42```.
1. Return ```kernel32``` handle when app requests ```mfc42```.

This solves the ```pidgen.dll``` issue, and should allow the games to run.
*Full credit goes to @aeikum for this proposal.*

## Games for which a stub would fix the issue:
#17 (https://github.com/ValveSoftware/Proton/issues/2624#issuecomment-562839599)

## Games which seem to need a full implementation of *MFC42.dll*:
#1593
#1805
#2623
#2728

## Related Wine bugreport:
https://bugs.winehq.org/show_bug.cgi?id=657

### PR DESCRIPTION
**Pull request by Sbte**
For some applications mfc42 is loaded, but never actually used. We can add Steam game IDs when we find more of such applications.

Closes ValveSoftware/Proton#2624

Note that there are more games mentioned in that issue, but I haven't verified that they are actually fixed by this hack, so I didn't include those in the patch.

### CODE REVIEW

**Comment by Sbte** [comment]
Actually, this should probably be done only after the dll was not found, so a user can still always supply their own mfc42. I'll fix the patch later and also test it for the other games.

**Comment by Sbte** [comment]
I updated the patch and confirmed that it only does something useful for AoE3. The other games mentioned in the Proton issue still crash because of missing mfc42 functionality. There are other older games that may benefit from this, but they are not available on Steam.

**Comment by aeikum** [comment]
Looks good, will merge.

**Comment by leillo1975** [comment]
GT Legends needs this dll:
https://github.com/ValveSoftware/Proton/issues/2728
it would be good not to install it separately. I hope you will find a solution

**Comment by Sbte** [comment]
I tested GT Legends with the hack (as stated in ValveSoftware/Proton#2624), and it doesn't help. It needs an actual implementation.

**Comment by aeikum** [comment]
This was merged as 304683886016ec940a9b331ce33fcbaf47e893c3.

**Pull request closed without merging**
