### PR TITLE
Fixing E. South America Standard Time DST starting date.

### PR DESCRIPTION
**Pull request by saboya**
Based on the discussion on https://github.com/ValveSoftware/Proton/issues/944#issuecomment-417303447.

Details on the date change: http://mm.icann.org/pipermail/tz-announce/2018-January/000048.html

### CODE REVIEW

**Comment by kisak-valve** [comment]
Hello @saboya, this probably should go to upstream wine.

**Comment by saboya** [comment]
@kisak-valve Agreed, I just thought it would benefit end-users faster if it landed here first, but I'm not sure how often you sync with the main wine tree or how you handle patches.

I'll try to send them to the winedevel list. Thanks!

**Comment by aeikum** [comment]
Hey @saboya, any progress on getting this upstreamed?

**Comment by saboya** [comment]
@aeikum I'm going to send the patch to wine-devel today or tomorrow, have some time constraints right now.

**Comment by zfigura** [comment]
For records' sake, this is being tracked upstream at https://bugs.winehq.org/show_bug.cgi?id=45786.

**Comment by saboya** [comment]
https://www.winehq.org/pipermail/wine-devel/2018-September/131932.html

**Comment by saboya** [comment]
That was quick: https://source.winehq.org/git/wine.git/commit/b29cdbd5f23548d9631e5c98ec923b6d2d16a3f8

I guess I can close this :)

**Comment by aeikum** [comment]
Thanks @saboya! This will work its way into Proton in the near future.

**Pull request closed without merging**
