### PR TITLE
XACT fixes

### PR DESCRIPTION
**Pull request by flibitijibibo**
For some reason I used the IIDs and not the CLSIDs... this is needed to fix support for games like https://github.com/ValveSoftware/Proton/issues/1809.

### CODE REVIEW

**Comment by aeikum** [comment]
Thanks, will merge.

**Comment by flibitijibibo** [comment]
Pushed one more commit to this PR, since it applies to the same game... the second commit is a series of fixes needed for Neptunia VIIR. Combined with the latest FAudio, the game should boot and run again.

**Comment by flibitijibibo** [comment]
One more commit (sorry Andrew ;_;), now that FACTFileIOCallbacks is supported we can use proper Win32 read functions to support XACT games. This fixes yet another Neptunia issue that caused streaming WaveBanks to get misread.

**Comment by aeikum** [comment]
No problem, 3 commits picked so far.

**Comment by flibitijibibo** [comment]
This got taken care of by 3.16-6.

**Pull request closed without merging**
