### PR TITLE
Fix for Path of Exile

### PR DESCRIPTION
**Pull request by ghost**
Partially fixes https://github.com/ValveSoftware/Proton/issues/58

### CODE REVIEW

**Comment by GloriousEggroll** [comment]
I think the patch by DataBeaver in the PoE issue on the proton repo is a little better/safer to use as it handles the call more gracefully:

https://gist.github.com/DataBeaver/5e1f1a256c7f1abb339831fc2b72a5db

**Comment by MrSapps** [comment]
The caller should have called CoInitialize before CoCreateInstance.. seems unlikely this is "correct" to me..

**Comment by cjwijtmans** [comment]
> The caller should have called CoInitialize before CoCreateInstance.. seems unlikely this is "correct" to me..

nowhere do i read from microsoft docs that CoInitialize must be called before CoCreateInstance, unless i am misunderstanding the docs since i dont know enough about ole.

**Comment by aeikum** [comment]
Hello, this was fixed in Proton with e2ac9b7e3, a27b3269eb9, and 7af29148112. Two of those were upstreamed, one didn't make it in.

**Pull request closed without merging**
