### PR TITLE
crypt32: Strictly honor NULL parm in CryptBinaryToStringW

### PR DESCRIPTION
**Pull request by ryao**
This fixes the segfault issue in ValveSoftware/Proton#298. I need to wait for the wine-devel mailing list administrator to approve my request to join the mailing list before I can send the patch upstream and I wnat to get this fixed in Proton sooner, rather than later, so I am submitting it here first.

### CODE REVIEW

**Comment by nsivov** [comment]
As already discussed in https://bugs.winehq.org/show_bug.cgi?id=44405 this is not a correct fix, is only pointing at the crash location.

**Comment by ryao** [comment]
@nsivov I have revised this in a way that should be more correct, although there are a few loose ends:

1. No test cases yet.
2. I am still unable to attach a debugger to see what is happening here, so my understanding of the control flow is incomplete.

What is certain right now is that the revised version fixes a real problem in the current implementation where it will perform a comparison against potentially uninitialized data when a NULL parameter is set. Furthermore, this code should have done early exit when passed NULL from the start.

Is this okay for Proton in the short term or will it block on the full fix at upstream Wine? If it is the latter, one of us should close this. I can always reopen it when the full fix is ready in upstream Wine.

**Comment by ryao** [comment]
I am withdrawing this due to a lack of time. :/

**Comment by nsivov** [comment]
No need to close, if it's still an issue. I can take a look at adding tests for this.

**Pull request closed without merging**
