### PR TITLE
winevulkan: Implement VK_KHR_get_surface_capabilities2 and fake support for VK_EXT_full_screen_exclusive

### PR DESCRIPTION
**Pull request by misyltoad**
We need this for some upcoming titles.

### CODE REVIEW

**Review by DadSchoorse — APPROVED** [review]

**Comment by DadSchoorse** [comment]
You changed the permissions of `make_vulkan` from 755 to 644, I think that's not what we want. :frog:
Also, it's intended that you didn't regenerate everything, isn't it? Not sure what proton-wine pull requests are supposed to do there.

**Comment by aeikum** [comment]
This was merged as 76b85105b27c346475fc1eb422dbdd03913f5014.

**Comment by spirit-q2** [comment]
does anyone know why this commit didn't make it to 6.3? I was able to launch the Doom Eternal on Ubuntu only when I found this PR and switched my Proton to 5.0 :roll_eyes:

**Comment by kisak-valve** [comment]
Hello @spirit-q2, I did a non-comprehensive search and it looks like this was replaced by upstream commits including https://github.com/ValveSoftware/wine/commit/086c686e817a596e35c41dd5b37f3c28587af9d5 https://github.com/ValveSoftware/wine/commit/314cd9cdd542db658ce7a01ef0a7621fc2d9d335.

**Comment by aeikum** [comment]
I think the fullscreen support part may have gotten dropped. I'm not certain whether those commits you point to are a complete replacement for the surface capabilities part or not. @Joshua-Ashton are you able to take a look?

**Comment by spirit-q2** [comment]
I agree, @kisak-valve, that looks like a replacement of this fix, but... if you will take a look [here](https://github.com/ValveSoftware/wine/blob/proton_6.3/dlls/winevulkan/make_vulkan#L95) you can see that the `VK_EXT_full_screen_exclusive` is excluded from the list of supported extensions in the current version.

I've tried so many variations and combinations to start Doom Eternal (including compiling the latest version of the `vulkan-loader`) and none of them worked. At the same time, the very first try to launch the Doom Eternal with Proton 5.0 (which includes this fix) succeeded!

**Comment by aeikum** [comment]
I was looking into restoring this support, but Doom Eternal is working fine for me in current Proton 6.3-7 without it. If we don't know if any games that need it, I'm not sure it's worth carrying a diff for.

@spirit-q2, I wonder if the failure you're seeing is unrelated to this change? Can you upload a log of the failure you're seeing with a current Proton release?

**Comment by spirit-q2** [comment]
<details><summary>

@aeikum what exact logs do you want to see? I was able to understand why it's not working for me only when I run the Doom Eternal with `+in_terminal 1` parameter. So it was logs from the Doom itself, not proton's. with `Proton - Experimental` it looks like this:

</summary><p>

```
spirit@ubuntu-pc:/d/games/id/DOOMEternal$ ./run.sh
Proton: Error while copying to "/home/spirit/.steam/steam/steamapps/compatdata/123-doom-eternal-install/pfx/drive_c/windows/system32/_nvngx.dll": No such file or directory
esync: up and running.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0
wine: configuration in L"/home/spirit/.steam/steam/steamapps/compatdata/123-doom-eternal-install/pfx" has been updated.
------ Initializing File System ------
Current search path:
        - C:/users/steamuser/Saved Games/id Software/DOOMEternal/base/
        - Z:/d/games/id/DOOMEternal/base/
------ File System initialized.
WARNING: idBroadcastManager::Register called with out of range system ID [65535]
----- Registering decl types -----
----- Starting decls parse jobs -----
Added structured log listener print-redirect
WARNING: idBroadcastManager::Register called with out of range system ID [65535]
WARNING: idBroadcastManager::Register called with out of range system ID [65535]
------ Command Line ------
 DOOMEternalx64vk.exe +set com_skipIntroVideo 1 +menu_advanced_AllowAllSettings 1 +in_terminal 1
2021-10-22T13:30:46.359+03:00 LOG: Command Line: DOOMEternalx64vk.exe +set com_skipIntroVideo 1 +menu_advanced_AllowAllSettings 1 
+in_terminal 1
------ OS Information ------
        Microsoft Windows 10 Build 18363

------ CPU Information ------
        Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
        1 CPU package, 4 physical cores, 8 logical cores
        2.6 GHz         Intel CPU with MMX & SSE & SSE2 & SSE3 & SSSE3 & SSE41 & SSE42 & AVX & HTT
        32768 kB 1st level cache, 262144 kB 2nd level cache, 6291456 kB 3rd level cache
        31.23 GB System Memory

idLib::SetProduction( PROD_PRODUCTION )
------- Initializing renderSystem --------
PreliminaryRenderSetup
...registered window class
MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

-------------------------
Application Info
-------------------------
App    : DOOMEternal - 1.0.2
Engine : idTech - 7.1.1
-------------------------
Instance Extensions
-------------------------
 + VK_KHR_surface
 + VK_KHR_win32_surface
 + VK_KHR_get_surface_capabilities2
Initialized stack tracer
FATAL ERROR: Please update your driver: VK_EXT_full_screen_exclusive is required.
wine: Unhandled exception 0x80000003 in thread 150 at address 0000000140822626 (thread 0150), starting debugger...
0x0000000140822626 EntryPoint+0xfe484e82 in doometernalx64vk: int       $3
Modules:
Module  Address                                 Debug info      Name (46 modules)
PE                d40000-          e3c000       Deferred        oo2core_8_win64
PE                e40000-          f6e000       Deferred        codex64
PE              7b000000-        7b0d5000       Deferred        kernelbase
PE              7b600000-        7b812000       Deferred        kernel32
PE              7bc00000-        7bc9e000       Deferred        ntdll
PE             140000000-       1469bb000       Export          doometernalx64vk
PE             180000000-       18007b000       Deferred        bink2w64
PE             1c8b40000-       1c8b60000       Deferred        msacm32
PE             1c8db0000-       1c8e3d000       Deferred        msvcrt
PE             1d7cb0000-       1d7cc1000       Deferred        wsock32
PE             1d97a0000-       1d97a7000       Deferred        api-ms-win-core-fibers-l1-1-1
PE             205950000-       205958000       Deferred        api-ms-win-appmodel-runtime-l1-1-2
PE             21a7e0000-       21a855000       Deferred        setupapi
PE             231ae0000-       231b62000       Deferred        rpcrt4
PE             23d820000-       23da48000       Deferred        user32
PE             243540000-       2435c6000       Deferred        gdiplus
PE             2522e0000-       252333000       Deferred        oleacc
PE             253cc0000-       253cd0000       Deferred        xinput1_3
PE             26b4c0000-       26b642000       Deferred        gdi32
PE             2739c0000-       273af6000       Deferred        oleaut32
PE             2bcfe0000-       2bcfed000       Deferred        mswsock
PE             2d4d40000-       2d4d57000       Deferred        bcrypt
PE             2e3540000-       2e3591000       Deferred        shlwapi
PE             2e8f10000-       2e9028000       Deferred        ole32
PE             2f1fa0000-       2f1fad000       Deferred        version
PE             2f7230000-       2f725d000       Deferred        uxtheme
PE             30c980000-       30c988000       Deferred        api-ms-win-core-synch-l1-2-0
PE             3126f0000-       312709000       Deferred        shcore
PE             327020000-       327072000       Deferred        combase
PE             32a700000-       32a729000       Deferred        sechost
PE             32f9a0000-       32f9ab000       Deferred        msimg32
PE             330260000-       33029f000       Deferred        advapi32
PE             346ba0000-       346bc0000       Deferred        jsproxy
PE             351680000-       351688000       Deferred        api-ms-win-core-localization-l1-2-1
PE             358120000-       358164000       Deferred        winhttp
PE             3785e0000-       3785ec000       Deferred        vulkan-1
PE             3af670000-       3af728000       Deferred        ucrtbase
PE             3afd00000-       3afd1a000       Deferred        imm32
PE             3b8f00000-       3b8fb7000       Deferred        winmm
PE             3be590000-       3be700000       Deferred        dbghelp
PE          7fe899790000-    7fe899794000       Deferred        winex11
PE          7fe89a0e0000-    7fe89a0eb000       Deferred        winspool
PE          7fe89a130000-    7fe89aa07000       Deferred        shell32
PE          7fe89ab50000-    7fe89ab54000       Deferred        ws2_32
PE          7fe89abd0000-    7fe89abd4000       Deferred        iphlpapi
PE          7fe89ae70000-    7fe89ae74000       Deferred        winevulkan
Threads:
process  tid      prio (all id:s are in hex)
00000020 steam.exe
        00000024    0
00000030 services.exe
        00000034    0
        00000038    0
        00000044    0
        00000054    0
        00000064    0
        0000007c    0
        00000088    0
        000000ac    0
        000000dc    0
0000003c winedevice.exe
        00000040    0
        0000004c    0
        00000050    0
        00000058    0
0000005c plugplay.exe
        00000060    0
        00000068    0
        0000006c    0
        00000070    0
        00000090    0
00000074 winedevice.exe
        00000078    0
        00000080    0
        00000084    0
        0000008c    0
        00000098    0
        0000009c    0
        000000a0    0
000000a4 svchost.exe
        000000a8    0
        000000b0    0
        000000b4    0
000000b8 tabtip.exe
        000000bc    0
        000000fc    0
        00000100    0
000000c0 explorer.exe
        000000c4    0
        000000c8    0
        000000cc    0
000000d4 rpcss.exe
        000000d8    0
        000000e4    0
        000000e8    0
        000000ec    0
        000000f0    0
        000000f4    0
00000144 conhost.exe
        00000148    0
0000014c (D) Z:\d\games\id\DOOMEternal\DOOMEternalx64vk.exe
        00000150    2 <==
        00000154    0
        00000158    0
        0000015c    0
        00000160    0
        00000164    0
        00000168    0
        0000016c    0
        00000170    0
        00000174   -1
        00000178    0
        0000017c    0
        00000180    0
        00000184    0
        00000188    0
        0000018c    0
        00000190    0
        00000194    0
        00000198    0
        0000019c    0
        000001a4    2
        000001a8    2
        000001ac    1
        000001b0   -2
        000001b4   -2
        000001b8   -2
        000001c4    0
System information:
    Wine build: wine-6.3
    Platform: x86_64
    Version: Windows 10
    Host system: Linux
    Host version: 5.11.0-38-generic
```

</p></details>

**Comment by spirit-q2** [comment]
<details><summary>

and on the `Proton 6.3`:

</summary><p>

```
spirit@ubuntu-pc:/d/games/id/DOOMEternal$ ./run.sh
++ export DXVK_ASYNC=1
++ DXVK_ASYNC=1
++ export DXVK_HUD=full
++ DXVK_HUD=full
++ LANG=ru_RU.UTF-8
++ proton4.sh DOOMEternalx64vk.exe +set com_skipIntroVideo 1 +menu_advanced_AllowAllSettings 1 +in_terminal 1
+ export SteamAppId=123-doom-eternal-p6.3
+ SteamAppId=123-doom-eternal-p6.3
+ export STEAM_COMPAT_CLIENT_INSTALL_PATH=/home/spirit/.steam/steam
+ STEAM_COMPAT_CLIENT_INSTALL_PATH=/home/spirit/.steam/steam
+ STEAM_APPS_PATH=/home/spirit/.steam/steam/steamapps
+ export STEAM_COMPAT_DATA_PATH=/home/spirit/.steam/steam/steamapps/compatdata/123-doom-eternal-p6.3
+ STEAM_COMPAT_DATA_PATH=/home/spirit/.steam/steam/steamapps/compatdata/123-doom-eternal-p6.3
+ mkdir -p /home/spirit/.steam/steam/steamapps/compatdata/123-doom-eternal-p6.3
+ PROTON_PATH='/home/spirit/.steam/steam/steamapps/common/Proton 6.3'
+ PROTON_EXEC='/home/spirit/.steam/steam/steamapps/common/Proton 6.3/proton'
+ python3 '/home/spirit/.steam/steam/steamapps/common/Proton 6.3/proton' run DOOMEternalx64vk.exe +set com_skipIntroVideo 1 +menu_advanced_AllowAllSettings 1 +in_terminal 1
Proton: Error while copying to "/home/spirit/.steam/steam/steamapps/compatdata/123-doom-eternal-p6.3/pfx/drive_c/windows/system32/_nvngx.dll": No such file or directory
esync: up and running.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

------ Initializing File System ------
Current search path:
        - C:/users/steamuser/Saved Games/id Software/DOOMEternal/base/
        - Z:/d/games/id/DOOMEternal/base/
------ File System initialized.
WARNING: idBroadcastManager::Register called with out of range system ID [65535]
----- Registering decl types -----
----- Starting decls parse jobs -----
Added structured log listener print-redirect
WARNING: idBroadcastManager::Register called with out of range system ID [65535]
WARNING: idBroadcastManager::Register called with out of range system ID [65535]
------ Command Line ------
 DOOMEternalx64vk.exe +set com_skipIntroVideo 1 +menu_advanced_AllowAllSettings 1 +in_terminal 1
2021-10-22T13:56:54.789+03:00 LOG: Command Line: DOOMEternalx64vk.exe +set com_skipIntroVideo 1 +menu_advanced_AllowAllSettings 1 
+in_terminal 1
------ OS Information ------
        Microsoft Windows 10 Build 17763

------ CPU Information ------
        Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
        1 CPU package, 4 physical cores, 8 logical cores
        3.5 GHz         Intel CPU with MMX & SSE & SSE2 & SSE3 & SSSE3 & SSE41 & SSE42 & AVX & HTT
        32768 kB 1st level cache, 262144 kB 2nd level cache, 6291456 kB 3rd level cache
        31.23 GB System Memory

idLib::SetProduction( PROD_PRODUCTION )
------- Initializing renderSystem --------
PreliminaryRenderSetup
...registered window class
MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

Initialized stack tracer
-------------------------
Application Info
-------------------------
App    : DOOMEternal - 1.0.2
Engine : idTech - 7.1.1
-------------------------
Instance Extensions
-------------------------
 + VK_KHR_surface
 + VK_KHR_win32_surface
 + VK_KHR_get_surface_capabilities2
FATAL ERROR: Please update your driver: VK_EXT_full_screen_exclusive is required.
wine: Unhandled exception 0x80000003 in thread c4 at address 0000000140822626 (thread 00c4), starting debugger...
0x0000000140822626 EntryPoint+0xfe484e82 in doometernalx64vk: int       $3
Modules:
Module  Address                                 Debug info      Name (45 modules)
PE                d40000-          e3c000       Deferred        oo2core_8_win64
PE                e40000-          f6e000       Deferred        codex64
PE              7b000000-        7b0d5000       Deferred        kernelbase
PE              7b600000-        7b812000       Deferred        kernel32
PE              7bc00000-        7bc9e000       Deferred        ntdll
PE             140000000-       1469bb000       Export          doometernalx64vk
PE             180000000-       18007b000       Deferred        bink2w64
PE             1c8b40000-       1c8b60000       Deferred        msacm32
PE             1d7cb0000-       1d7cc1000       Deferred        wsock32
PE             1d97a0000-       1d97a7000       Deferred        api-ms-win-core-fibers-l1-1-1
PE             205950000-       205958000       Deferred        api-ms-win-appmodel-runtime-l1-1-2
PE             21a7e0000-       21a854000       Deferred        setupapi
PE             231ae0000-       231b62000       Deferred        rpcrt4
PE             23d820000-       23da47000       Deferred        user32
PE             243540000-       2435c6000       Deferred        gdiplus
PE             2522e0000-       252332000       Deferred        oleacc
PE             253cc0000-       253cd0000       Deferred        xinput1_3
PE             26b4c0000-       26b642000       Deferred        gdi32
PE             2739c0000-       273af6000       Deferred        oleaut32
PE             2bcfe0000-       2bcfed000       Deferred        mswsock
PE             2d4d40000-       2d4d57000       Deferred        bcrypt
PE             2e3540000-       2e3591000       Deferred        shlwapi
PE             2e8f10000-       2e9028000       Deferred        ole32
PE             2f1fa0000-       2f1fad000       Deferred        version
PE             2f7230000-       2f725d000       Deferred        uxtheme
PE             30c980000-       30c988000       Deferred        api-ms-win-core-synch-l1-2-0
PE             3126f0000-       312709000       Deferred        shcore
PE             327020000-       327072000       Deferred        combase
PE             32a700000-       32a729000       Deferred        sechost
PE             32f9a0000-       32f9ab000       Deferred        msimg32
PE             330260000-       33029f000       Deferred        advapi32
PE             346ba0000-       346bc0000       Deferred        jsproxy
PE             351680000-       351688000       Deferred        api-ms-win-core-localization-l1-2-1
PE             358120000-       358164000       Deferred        winhttp
PE             3785e0000-       3785ec000       Deferred        vulkan-1
PE             3af670000-       3af728000       Deferred        ucrtbase
PE             3afd00000-       3afd1a000       Deferred        imm32
PE             3b8f00000-       3b8fb7000       Deferred        winmm
PE             3be590000-       3be700000       Deferred        dbghelp
PE          7f6f0b390000-    7f6f0b394000       Deferred        winex11
PE          7f6f0bcd0000-    7f6f0bcdb000       Deferred        winspool
PE          7f6f0bd30000-    7f6f0c607000       Deferred        shell32
PE          7f6f0c750000-    7f6f0c754000       Deferred        ws2_32
PE          7f6f0c7d0000-    7f6f0c7d4000       Deferred        iphlpapi
PE          7f6f0ca50000-    7f6f0ca54000       Deferred        winevulkan
Threads:
process  tid      prio (all id:s are in hex)
00000020 steam.exe
        00000024    0
00000030 services.exe
        00000034    0
        00000038    0
        00000044    0
        00000048    0
        00000054    0
        00000064    0
        0000007c    0
        00000088    0
        000000ac    0
        00000104    0
        00000108    0
0000003c winedevice.exe
        00000040    0
        0000004c    0
        00000050    0
        00000058    0
0000005c plugplay.exe
        00000060    0
        00000068    0
        0000006c    0
        00000070    0
        00000090    0
        00000094    0
00000074 winedevice.exe
        00000078    0
        00000080    0
        00000084    0
        0000008c    0
        00000098    0
        0000009c    0
        000000a0    0
000000a4 svchost.exe
        000000a8    0
        000000b0    0
        000000b4    0
000000b8 conhost.exe
        000000bc    0
000000c0 (D) Z:\d\games\id\DOOMEternal\DOOMEternalx64vk.exe
        000000c4    2 <==
        000000c8    0
        000000cc    0
        000000d0    0
        000000d4    0
        000000d8    0
        000000dc    0
        000000e0    0
        000000e4    0
        00000124   -1
        00000128    0
        0000012c    0
        00000130    0
        00000134    0
        00000138    0
        0000013c    0
        00000140    0
        00000144    0
        00000148    0
        0000014c    0
        00000154    2
        00000158    2
        0000015c    1
        00000160   -2
        00000164   -2
        00000168   -2
        00000174    0
000000e8 explorer.exe
        000000ec    0
        000000f0    0
        000000f4    0
000000fc rpcss.exe
        00000100    0
        0000010c    0
        00000110    0
        00000114    0
        00000118    0
        0000011c    0
        00000120    0
System information:
    Wine build: wine-6.3
    Platform: x86_64
    Version: Windows 10
    Host system: Linux
    Host version: 5.11.0-38-generic
```

</p></details>

**Comment by spirit-q2** [comment]
<details><summary>

at the same time, here is the beginning of logs with `Proton 5.0`:

</summary><p>

```
./run.sh
esync: up and running.
------ Initializing File System ------
Current search path:
	- C:/users/steamuser/Saved Games/id Software/DOOMEternal/base/
	- Z:/d/games/id/DOOMEternal/base/
------ File System initialized.
WARNING: idBroadcastManager::Register called with out of range system ID [65535]
----- Registering decl types -----
----- Starting decls parse jobs -----
Added structured log listener print-redirect
WARNING: idBroadcastManager::Register called with out of range system ID [65535]
WARNING: idBroadcastManager::Register called with out of range system ID [65535]
------ Command Line ------
 DOOMEternalx64vk.exe +set com_skipIntroVideo 1 +menu_advanced_AllowAllSettings 1 +in_terminal 1
2021-10-22T13:58:38.435+03:00 LOG: Command Line: DOOMEternalx64vk.exe +set com_skipIntroVideo 1 +menu_advanced_AllowAllSettings 1 +in_terminal 1
------ OS Information ------
	Microsoft Windows 10 Build 17134

------ CPU Information ------
	Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
	1 CPU package, 4 physical cores, 8 logical cores
	3.5 GHz 	Intel CPU with MMX & SSE & SSE2 & SSE3 & SSSE3 & SSE41 & SSE42 & AVX & HTT
	32768 kB 1st level cache, 262144 kB 2nd level cache, 6291456 kB 3rd level cache
	31.23 GB System Memory

idLib::SetProduction( PROD_PRODUCTION )
------- Initializing renderSystem --------
PreliminaryRenderSetup
...registered window class
MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

-------------------------
Application Info
-------------------------
App    : DOOMEternal - 1.0.2
Engine : idTech - 7.1.1
-------------------------
Instance Extensions
-------------------------
 + VK_KHR_surface
 + VK_KHR_win32_surface
 + VK_KHR_get_surface_capabilities2

-------------------------
Vulkan Device Info:
-------------------------
Vendor : NVIDIA
GPU    : NVIDIA GeForce GTX 1050 Ti
VRAM   : 4342 MiB
Driver : 470.63.01 (758fc040)
VK API : 1.2.175


-------------------------
Device Extensions
-------------------------
 + VK_KHR_swapchain
 + VK_KHR_dedicated_allocation
 + VK_NV_dedicated_allocation_image_aliasing
 + VK_KHR_8bit_storage
 + VK_KHR_16bit_storage
 + VK_KHR_shader_float16_int8
 + VK_EXT_descriptor_indexing
 + VK_EXT_full_screen_exclusive
 + VK_KHR_driver_properties
Initializing Vulkan subsystem
ShowGameWindow: (160, 73) 1600 x 900, windowed
RENDER THREAD STACK SIZE: 4194304
WARNING: idBroadcastManager::ReleaseBroadcastEvent called with out of range system ID [65535]
Executing default.cfg for device #0...
Executing default.cfg for device #1...
Executing default.cfg for device #2...
Executing default.cfg for device #3...
Unknown command 'build_candidateURL'
Unknown command 'build_candidateRecipeDescription'
Unknown command 'build_binaryBranch'
Unknown command 'build_binaryChange'
Unknown command 'build_packageParent'
Unknown command 'build_packageMapSet'
Unknown command 'build_packageBranch'
------ Build Information ------
	Host Name: UBUNTU-PC
	Binary Build:
		Version: 7.1.1
		Target: shippingretail
		Name: 20200313-160111-violet-almond
		Branch: release-pc-gmc
		Requestor: user:ben.miles:ff818
		URL: http://www.eden.idsoftware.com/builds/binaries/20200313-160111-violet-almond
		Relevant CLs: 1052055
	Package:
		Name: 20200306-145343-asphalt-drill
		Requestor: user:ben.miles:ff818
		URL: http://www.eden.idsoftware.com/builds/packages/20200306-145343-asphalt-drill
		Relevant CLs: 1049067
	Disc Layout:
		Name: 20200313-160407-helium-fudge
	Candidate:
		Name: 20200313-160408-ill-finch
		Disc Number: 1
2021-10-22T13:58:39.235+03:00 LOG: Retrieved build information
Reading strings/russian.blang
reading 11048 strings
11048 strings read
```

</p></details>

check the `Device Extensions` section :)

**Comment by spirit-q2** [comment]
it also might be related to my version of Doom Eternal... it's not the "steam version", if you know what I mean ;)

**Comment by Vash63** [comment]
> it also might be related to my version of Doom Eternal... it's not the "steam version", if you know what I mean ;)

The Bethesda.net version should be updated also, if not you may want to contact Bethesda to see if they are behind on patching on their official launcher. There are no other versions on PC. I don't think anyone here cares about pirated versions or people who are trying to get support for them.

**Comment by kisak-valve** [comment]
Hello @spirit-q2, in the future, please use a [gist](https://gist.github.com) or other pastebin service and share a link or attach logs as a file instead of copy/pasting large blobs of text inline with your comments.

**Comment by spirit-q2** [comment]
sure @kisak-valve will do. btw, how did you make them to be collapsed? :thinking:

**Comment by kisak-valve** [comment]
You can click on the edit option of your previous comment to see the html trick I used.

**Pull request closed without merging**
